require_relative 'vhdl_helpers'
module Reggae
  class Generator
    include VHDL::Helpers
    def reggae_header
      code=Code.new
      code << comment("--"*40)
      code << comment("Automatically generated by Reggae EDA tool")
      code << comment("Copyright Jean-Christophe Le Lann")
      code << comment("--"*40)
      code << comment("date : d/m/y #{Time.now.strftime("%d/%m/%Y at %k:%M")}")
      code << comment("--"*40)
      code
    end
  end
end
